import { ChatRoom } from "./types";

export const chatRooms: ChatRoom[] = [
  {
    id: "1",
    title: "Chat Room 1",
    description: "Chat Room 1 Description",
    isPrivate: false,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Chat Room 2",
    description: "Chat Room 2 Description",
    isPrivate: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const dummyMessages: any[] = [
  {
    $id: "msg-1",
    $createdAt: "2025-01-10T12:30:00.000Z",
    $updatedAt: "2025-01-10T12:30:00.000Z",
    $collectionId: "messages",
    $databaseId: "chat-app",
    $permissions: [],
    content: "Hey everyone! Welcome to the new chat room 🎉",
    senderId: "user-1",
    senderName: "Karim",
    senderPhoto: "https://randomuser.me/api/portraits/men/32.jpg",
    chatRoomId: "room-1",
  },
  {
    $id: "msg-2",
    $createdAt: "2025-01-10T12:32:00.000Z",
    $updatedAt: "2025-01-10T12:32:00.000Z",
    $collectionId: "messages",
    $databaseId: "chat-app",
    $permissions: [],
    content: "Hello Karim!",
    senderId: "user-2",
    senderName: "Mona",
    senderPhoto: "https://randomuser.me/api/portraits/women/44.jpg",
    chatRoomId: "room-1",
  },
  {
    $id: "msg-3",
    $createdAt: "2025-01-10T12:35:00.000Z",
    $updatedAt: "2025-01-10T12:35:00.000Z",
    $collectionId: "messages",
    $databaseId: "chat-app",
    $permissions: [],
    content: "Shall we start planning our project?",
    senderId: "user-3",
    senderName: "Omar",
    senderPhoto: "https://randomuser.me/api/portraits/men/12.jpg",
    chatRoomId: "room-1",
  },
  {
    $id: "msg-4",
    $createdAt: "2025-01-10T12:40:00.000Z",
    $updatedAt: "2025-01-10T12:40:00.000Z",
    $collectionId: "messages",
    $databaseId: "chat-app",
    $permissions: [],
    content: "Yes, I think that’s a good idea. Let’s assign tasks.",
    senderId: "user-2",
    senderName: "Mona",
    senderPhoto: "https://randomuser.me/api/portraits/women/44.jpg",
    chatRoomId: "room-1",
  },
];
